site_name:        GoogleCloud.jl
repo_url:         https://github.com/joshbode/GoogleCloud.jl
site_description: Google Cloud JSON APIs for Julia

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Custom APIs:
    - Collections: custom_api/index.md
    - Key Store: custom_api/keystore.md
  - API Documentation:
    - Credentials: api/credentials.md
    - Sessions: api/session.md
    - API Representation: api/api.md
    - API Root URLs: api/root.md
    - Error Types: api/error.md
